import EditorWrapper from '@/components/EditorWrapper';
import { Box } from '@chakra-ui/react';
import { Inter } from 'next/font/google';
import Head from 'next/head';
import React from 'react';

const inter = Inter({ subsets: ['latin'] });

export default function Home() {
  const [tabIndex, setTabIndex] = React.useState(0);

  return (
    <>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <Box
        as="main"
        backgroundColor={'gray.50'}
        display={'flex'}
        flexDirection={'row'}
        h="100vh"
        w="100vw"
      >
        <EditorWrapper />
      </Box>
    </>
  );
}
